### ISSUE TITLE
open('foo', 'w').write('bar') not handled correctly

### ISSUE THREAD

**Issue by boxed** [jmcgeheeiv/pyfakefs#417] opened 2018-07-08 11:52 UTC
I had a program that did

```python
open('foo', 'w').write('bar')
```

(which is not ideomatic but in CPython works fine), and after that the file is just not there even though I was writing over an existing file created with `fs.create_file`.

**Comment by mrbean-bremen** [comment] 2018-07-08 13:36
Thanks for the report!
Hm, the following works fine for me, at least under Windows:
``` python
    def test_open_write(self):
        file_path = 'foo'
        self.fs.create_file(file_path)
        open(file_path, 'w').write('bar')
        self.assertTrue(os.path.exists(file_path))
```

This is using `fake_filesystem_unittest.TestCase`. Though generally it is not a good idea to do this as you don't have a file object to close the file now. Leaving the file open will probably not write the file contents - the caching/flushing behavior is different under different systems and different Python versions, so while we try to emulate this in `pyfakefs`, the behavior may not match in all cases.
What are your OS and Python version? Can you write a minimal test that succeeds in the real OS and fails under pyfakefs?

**Comment by boxed** [comment] 2018-07-08 13:37
macOS. I'm sorry, but I found like 5 more issues that were all fatal to my use of this lib, so have given up on the entire thing :(

**Comment by mrbean-bremen** [comment] 2018-07-08 13:55
that's unfortunate... ah well, it's obviously not suited for your use then.

**Comment by mrbean-bremen** [comment] 2018-07-08 13:58
I don't have a Mac, so I can test locally only under Linux and Windows - both did not show the problem.

**Comment by mrbean-bremen** [comment] 2018-07-08 14:36
Ok, the test also works under MacOS (tested in Travis.CI) - so I don't know what the problem is.
Closing this - feel free to reopen it if you want to have another go or have more information.

**Closed** 2018-07-08 14:36 UTC
