### ISSUE TITLE
How to mock existing Path objects?

### ISSUE THREAD

**Issue by mchwalisz** [jmcgeheeiv/pyfakefs#458] opened 2018-12-04 15:38 UTC
**Describe the bug**
How should I mock the `Path` object that is created at import? The following test shows exactly what I mean.

I'm not sure if it is a bug. It is for me an unexpected behavior. The created `Path` objects are not mocked and still refer to the real file system.

**How To Reproduce**
```python
from pathlib import Path
# import example
"""cat example.py
from pathlib import Path
here = Path("/example_home")
"""
here = Path("/example_home")

def do_something():
    example2 = Path("/example_home")
    if not example2.exists():
        raise FileNotFoundError()

def test_example_file(fs):
    fs.create_dir("/example_home")
    assert Path("/example_home").exists()
    assert here.exists()
    # assert example.here.exists()

def test_do_something(fs):
    fs.create_dir("/example_home")
    do_something()
```

Run `pytest`. `test_example_file` will fail.

**Your enviroment**

```
Linux-4.19.4-arch1-1-ARCH-x86_64-with-arch
Python 3.7.1 (default, Oct 22 2018, 10:41:28) 
[GCC 8.2.1 20180831]
pyfakefs 3.5.3
```

**Comment by mrbean-bremen** [comment] 2018-12-04 18:52
This is not a bug, but a shortcoming of pyfakefs - if you use a filesystem function to initialize a global variable (or a default argument), pyfakefs cannot detect this statically afterwards. If reloading the sut module in the test initialization, this would work, but there is no convenient way to do this with the `fs` fixture used in pytest.
There is some information about this in the [documentation](http://jmcgeheeiv.github.io/pyfakefs/release/usage.html#customizing-patcher-and-testcase) - if using `Patcher` or `UnitTest`, the `modules_to_reload` argument can be used. 

From the documentation:
**Note:** If you need these arguments in PyTest, you must use Patcher directly instead of the fs fixture. Alternatively, you can add your own fixture with the needed parameters.
An example for both approaches can be found in [pytest_fixture_test.py](https://github.com/jmcgeheeiv/pyfakefs/blob/master/pyfakefs/tests/pytest/pytest_fixture_test.py) with the example fixture in [conftest.py](https://github.com/jmcgeheeiv/pyfakefs/blob/master/pyfakefs/tests/pytest/conftest.py).

**Comment by mchwalisz** [comment] 2018-12-04 19:40
Thanks for the answer. To make sure I understand correctly. It will be enough if I either reload the module with `Patcher` or reinitialize the module global `Path` variable. In my use case, the latter seems more convenient. 

I would also recommend extending the **note** documentation on examples, in which cases `Patcher` is necessary. I have seen the note but was not sure if my case falls into that category.

**Comment by mrbean-bremen** [comment] 2018-12-04 20:51
> It will be enough if I either reload the module with Patcher or reinitialize the module global Path variable. 

Yes, that should be sufficient.

> I would also recommend extending the note documentation on examples

Good point - I think it makes sense to add more specific cases where this is needed. I will see to this later, thanks!

**Comment by mchwalisz** [comment] 2018-12-04 20:57
> Good point - I think it makes sense to add more specific cases where this is needed. I will see to this later, thanks!

Feel free to use above as example as well.

**Comment by mrbean-bremen** [comment] 2018-12-04 21:19
Please let us know it that worked for you.

**Comment by mchwalisz** [comment] 2018-12-05 10:05
With the following code, it works.

I figured out that the `SKIPMODULES` is actually a pretty important feature, as it allows `pytest` for file introspection. Again, I would like to see a better explanation in docs on which modules are actually important here.

```python
import pytest
import linecache
import tokenize
import py
import shepherd
import gpio
from pyfakefs.fake_filesystem_unittest import Patcher


Patcher.SKIPMODULES.add(py)
Patcher.SKIPMODULES.add(pytest)
Patcher.SKIPMODULES.add(tokenize)
Patcher.SKIPMODULES.add(linecache)


@pytest.fixture()
def patcher_fs():
    patcher = Patcher(modules_to_reload=[gpio])
    patcher.setUp()
    patcher.fs.create_dir("/sys/class/gpio")
    yield patcher
    patcher.tearDown()
```

**Comment by mrbean-bremen** [comment] 2018-12-05 18:58
Glad to hear that this works!
Regarding `SKIPMODULES` - this usually should not be needed to be changed by pyfakefs users, except for an own pytest plugin, where it shall be copied from the standard plugin or the example.
We did not add `pytest` to `SKIPMODULES` - it certainly makes sense to add this. Adding `tokenize` is sufficient in Python 3 - in the standard plugin, we do it another way that works both in Python 2 and 3.
Anyway, I will adapt both the standard plugin and the example to add pytest to `SKIPMODULES`, and to use the nicer `yield` syntax, and I will try to make the documentation more specific. 
Thanks for the input!

**Comment by mrbean-bremen** [comment] 2018-12-05 19:39
And while I checked this I found a bug for the pytest plugin in Python 2...

**Comment by mrbean-bremen** [comment] 2018-12-05 20:47
I have restructured [the documentation](http://jmcgeheeiv.github.io/pyfakefs/master/usage.html#customizing-patcher-and-testcase) a little bit - please check if this is more clear for you.

**Comment by mchwalisz** [comment] 2018-12-06 08:21
I agree it is much more clear now.

**Comment by mrbean-bremen** [comment] 2018-12-06 11:40
Ok, thanks - I'm closing this issue then.

**Closed by mrbean-bremen** 2018-12-06 11:40 UTC
Labels: question
