### ISSUE TITLE
shutil.copy error

### ISSUE THREAD

**Issue by benureau** [jmcgeheeiv/pyfakefs#105] opened 2016-06-05 19:37 UTC
I get an error relating to the `Hexlified` class having no `encode` method, when copying binary files inside the fake filesystem, using shutil.copy. I don't have the error on hand anymore, I can regenerate it if you need. I made a very crude fix for it, but I am sure there is a better way:
https://github.com/humm/pyfakefs/commit/8e702c441927e90ddf33a31bdda4765944380ab2

**Comment by mrbean-bremen** [comment] 2016-06-06 18:05
I think, SetContents() is not the right function to be used in copyfile() in this case.
I would propose to either directly assign the contents in copyfile(), or add a respective CopyContents() method (not sure about the coding guidelines here).

**Comment by mrbean-bremen** [comment] 2016-06-10 19:36
On a second thought, I find your fix better, with the exception that there is no need to decode and encode the contents in this case. I added a small test that reproduces the problem without the fix - will put it in a PR in a second.

**Comment by jmcgeheeiv** [comment] 2016-09-11 17:51
Closing due to @mrbean-bremen #108.

**Closed by jmcgeheeiv** 2016-09-11 17:51 UTC
