### ISSUE TITLE
OS and pyfakefs allow read on closed file, but differ in result

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#283] opened 2017-08-09 19:39 UTC
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)
opener0 = pyfakefs.fake_filesystem.FakeFileOpen(fs)

component0 = "alpha"
path0 = "/Volumes/ramdisk/test"
path0 += "/" + component0
bytes0 = 0
bytes0 += 1
str0 = ""
str0 += 'a'
str0 += 'n'
fd0 = os0.open(path0, os.O_CREAT | os.O_WRONLY | os.O_TRUNC)
os0.write(fd0,str0)
os0.close(fd0)
file0 = opener0(path0)
result = file0.read(bytes0)

print repr(result)

result = os0.read(fd0,bytes0)

print repr(result)

they agree on the first print ('a'), but OS produces '' for the second, while pyfakefs produces 'n'.  I'm not sure why either is allowing a read on fd0, which is supposed to be closed.

**Comment by mrbean-bremen** [comment] 2017-08-09 20:27
I think if I fix the other bug, this one will behave differently (e.g. not allow the read), which is still wrong, though I don't understand it either.

**Comment by mrbean-bremen** [comment] 2017-08-10 19:07
Ok, the thing here is that both OS and pyfakefs reuse the next free file descriptor for the new open file internally, which is the one of the recently closed file. What they don't agree on is the position in the file - pyfakefs uses the current position of the opened file, OS seems to use the position previously associated with the file descriptor. 
As far as I can see, this is undefined behavior - I'm not sure if we shall match the python behavior here (meaning we shall maintain the file positions for close file descriptors) - I would rather leave this as is.

**Comment by mrbean-bremen** [comment] 2017-08-15 20:32
@agroce - I don't consider this one as a bug; if you need this fixed for your tests, give me a note - otherwise I will will close it (same probably for the 2 other remaining bugs) .

**Comment by mrbean-bremen** [comment] 2017-08-17 20:22
Closing as not a bug, see previous comments.

**Closed by mrbean-bremen** 2017-08-17 20:22 UTC
Labels: TSTL
