### ISSUE TITLE
RecursionError implying pyfakefs inside a Pause(fs)

### ISSUE THREAD

**Issue by nicolashainaux** [jmcgeheeiv/pyfakefs#631] opened 2021-08-27 10:07 UTC
I'm not completely sure this is a bug, but this is troubling enough to open this issue and I hope this is possible to further investigate it.

Context is: at the end of a test, I want to operate on real files to put things back like they were before the test (the test is on a sqlite3 database that needs to be "reset" for the next time).

So, I use the `Pause` context manager, this way:

    with Pause(fs):
        empty_db = Path(__file__).parent / 'data/empty.sqlite3'
        empty_db.unlink()
        empty_db_copy = Path(__file__).parent / 'data/empty_copy.sqlite3'
        copy2(empty_db_copy, empty_db)

where `copy2` is imported from `shutil`.
`Pause` itself is imported this way: `from pyfakefs.fake_filesystem_unittest import Pause`

I use `pytest -vv` to run the tests.

I don't understand why I get an error that's related to pyfakefs (version 4.5.0), in spite of the `Pause(fs)`:

```
tests/04_commands_test.py::test_pair FAILED                                                                                                                                       [100%]

======================================================================================= FAILURES ========================================================================================
_______________________________________________________________________________________ test_pair _______________________________________________________________________________________

fs = <pyfakefs.fake_filesystem.FakeFilesystem object at 0x7f23fbeb1220>, mocker = <pytest_mock.plugin.MockerFixture object at 0x7f23fbeb12b0>

>   ???

/home/nico/.local/dev/zano/tests/04_commands_test.py:122: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/home/nico/.pyenv/versions/3.8.6/lib/python3.8/shutil.py:432: in copy2
    ???
/home/nico/.pyenv/versions/3.8.6/lib/python3.8/shutil.py:261: in copyfile
    ???
/home/nico/.local/dev/zano/.venv/py38/lib/python3.8/site-packages/pyfakefs/fake_filesystem.py:4634: in open
    ???
/home/nico/.pyenv/versions/3.8.6/lib/python3.8/traceback.py:211: in extract_stack
    ???
/home/nico/.pyenv/versions/3.8.6/lib/python3.8/traceback.py:366: in extract
    ???
/home/nico/.pyenv/versions/3.8.6/lib/python3.8/traceback.py:288: in line
    ???
/home/nico/.pyenv/versions/3.8.6/lib/python3.8/linecache.py:16: in getline
    ???
/home/nico/.pyenv/versions/3.8.6/lib/python3.8/linecache.py:47: in getlines
    ???
/home/nico/.pyenv/versions/3.8.6/lib/python3.8/linecache.py:136: in updatecache
    ???
/home/nico/.pyenv/versions/3.8.6/lib/python3.8/tokenize.py:392: in open
    ???
/home/nico/.local/dev/zano/.venv/py38/lib/python3.8/site-packages/pyfakefs/fake_filesystem.py:4634: in open
    ???
/home/nico/.pyenv/versions/3.8.6/lib/python3.8/traceback.py:211: in extract_stack
    ???
/home/nico/.pyenv/versions/3.8.6/lib/python3.8/traceback.py:366: in extract
    ???
/home/nico/.pyenv/versions/3.8.6/lib/python3.8/traceback.py:288: in line
    ???
E   RecursionError: maximum recursion depth exceeded
!!! Recursion detected (same locals & position)
================================================================================ short test summary info ================================================================================
FAILED tests/04_commands_test.py::test_pair - RecursionError: maximum recursion depth exceeded
============================================================================= 1 failed, 22 passed in 
0.66s ==============================================================================
```

The faulty line (number 122) is the `copy2` one.

I thought maybe this is related to the fact that I also did patch the `open` builtin. But I tried to separate this Pause block in another test, in order to "unpatch" open, and the result is exactly the same.

I don't know if there are any hints as to the reason for this issue...? I can provide more information if needed.

**Comment by nicolashainaux** [comment] 2021-08-28 14:58
Unfortunately, the code I have is not too simple. Having nothing better, I can still show you the code of the test (maybe there's something obviously wrong that you would recognize at first sight??).

Before that, I could find out a little something more. There's another test in my tests suite, namely `test_idb_creation`, where I use almost the same block (with a `copy2` inside a `Pause(fs)`). This first test never triggers the bug (yet it also patches `open`).

I gathered the offending lines of the buggy test in a separate "fake" test (not a test, really) :
```
def test_extraneous(fs):
    with Pause(fs):
        blank_db = Path(__file__).parent / 'data/blank.sqlite3'
        blank_db.unlink()
        blank_db_copy = Path(__file__).parent / 'data/blank_copy.sqlite3'
        shutil.copy2(blank_db_copy, blank_db)  # causes RecursionError
```
If I put `test_extraneous` anywhere in the tests suite, *after* `test_idb_creation`, then `test_extraneous` does trigger the bug. If I put it *before*, then there's no bug at all.

So it looks like the first test contains code that triggers the bug when using `copy2` inside a `Pause(fs)` another time, later.

Same problem if I write `test_extraneous` this way:
```
def test_extraneous():
    blank_db = Path(__file__).parent / 'data/blank.sqlite3'
    blank_db.unlink()
    blank_db_copy = Path(__file__).parent / 'data/blank_copy.sqlite3'
    shutil.copy2(blank_db_copy, blank_db)  # causes RecursionError
```
I already noticed that it looks like `pyfakefs` patches the file system everywhere in my tests suite, even if I do not write `fs` as argument of a test function. I think this is not normal, am I wrong?

If I remove `test_idb_creation`, then there's no bug at all.

So I guess the problem comes from this portion of code, even if it does not trigger the bug itself. Here it is, so far: (I'll try to investigate and simplify it to find out more narrowly what triggers the bug):

```
def test_idb_creation(mocker, fs):
    content = """[synced.side1]
name = 'HOME'
path = '/path/to/root1/'

[synced.side2]
name = 'NOMAD'
path = '/path/to/root2/'

[replicas]
"""
    mocker.patch('builtins.open', mocker.mock_open(read_data=content))
    testdb_path = ZANO_LOCAL_SHARE / 'CLG/inodes.sqlite3'
    b = Bundle('CLG')
    fs.create_dir(b.paths['dir'])
    fs.create_file(testdb_path)
    assert Path(b.paths['dir']).exists()
    with pytest.raises(FileExistsError) as excinfo:
        b.create_idb()
    assert str(excinfo.value) == '[Errno 17] File exists: '\
        f'PosixPath(\'{testdb_path}\')'
    empty_db = Path(__file__).parent / 'data/empty.sqlite3'
    mocked_CM = database.ContextManager(empty_db)
    mocker.patch('microlib.database.ContextManager', return_value=mocked_CM)
    fs.remove_object(b.paths['dir'])
    assert not Path(b.paths['dir']).exists()
    b.create_idb()
    assert Path(b.paths['db']).exists()
    with database.ContextManager(b.paths['db']) as cursor:
        idb = database.Operator(cursor)
        assert idb.table_exists('files')
        assert idb.table_exists('dirs')
        assert idb.get_table('files', include_headers=True) \
            == [('id', 'inode1', 'inode2')]
        assert idb.get_table('dirs', include_headers=True) \
            == [('id', 'inode1', 'inode2')]
    with Pause(fs):
        empty_db = Path(__file__).parent / 'data/empty.sqlite3'
        empty_db.unlink()
        empty_db_copy = Path(__file__).parent / 'data/empty_copy.sqlite3'
        copy2(empty_db_copy, empty_db)
```

**Comment by mrbean-bremen** [comment] 2021-08-28 15:16
Thank you for investigating this - the problem seems to be the `mock_open` call together with the `fs` fixture.
I can reproduce the problem now if I just do:
```py
def test_idb_creation(mocker, fs):
    mocker.patch('builtins.open', mocker.mock_open(read_data="content"))

def test_extraneous(fs):
    with Pause(fs):
        empty_db = Path(__file__).parent / 'test.txt'
        empty_db_copy = Path(__file__).parent / 'test_copy.txt'
        copy2(empty_db_copy, empty_db)
```
I haven't tried this before. It looks like the `fs` fixture is not correctly shut down in this case - I will see what I can find out.

**Comment by mrbean-bremen** [comment] 2021-08-28 16:48
I haven't checked for the cause yet, but in case you need to get it to work before it gets fixed (or I can't fix it), there seems to be an easy workaround: reverse the order of the fixtures, e.g.:
```py
def test_idb_creation(fs, mocker):
    mocker.patch('builtins.open', mocker.mock_open(read_data="content"))
   ...
```
The problem has probably to do with the fact that in the first case, `mock_open` does not mock the original `open`, but the patched `open`, and sets it back to that on exit (probably after `fs` has reverted it's patching). Though that is only a theory for now.

The other way to work around the problem is to not use `mock_open`, but just create the needed file in the fake filesystem:
```py
def test_idb_creation(fs):
    content = "Something useful"
    fs.create_file(file_path, contents=content)
```
This of course only works if you know the path of the file in question, but this is the usual pattern if working with `pyfakefs`.

**Comment by nicolashainaux** [comment] 2021-08-28 19:00
Great! Using `fs, mocker` does indeed solve the case!
On another hand, I will follow your advice and create a fake file via `fs.create_file()` anywhere it's possible, instead of patching `open`. This looks more flexible, and less complicated. Many thanks!!

**Comment by mrbean-bremen** [comment] 2021-08-29 17:43
Ok, I found more problems with `mock_open` if using `pyfakefs`. The problem is that `open` may be used during the `pyfakefs` initialization, and if it is mocked at that point, some things will go awry. Fixing this would be difficult and error-prone, I think, so I will probably just add a bit of documentation that states that as a limitation and shows how to work around it.

**Comment by nicolashainaux** [comment] 2021-08-29 19:22
Good! I've changed my code and the workaround works perfectly fine and is really not complicated! I think the issue can be closed.

**Comment by mrbean-bremen** [comment] 2021-08-29 19:23
Ok, thanks! Closing the issue in this case.

**Closed by mrbean-bremen** 2021-08-29 19:23 UTC
Labels: bug
