### ISSUE TITLE
GitHub Actions get stuck when using fs fixture and importing torch

### ISSUE THREAD

**Issue by mniebisch** [jmcgeheeiv/pyfakefs#693] opened 2022-07-20 13:42 UTC
Hey,

I'm using pyfakefs for a project. While writing tests locally, everything worked like a charm. 
At some point, I pushed my code and applied it to GitHub Action. During the test phase of my workflow, the tests just got stuck, and the workflow didn't terminate.

I tracked the problem down to a conflict between the fs fixture and the import of torch.
If torch is imported, all tests are executed until a test uses the fs fixture for the first time.

I reproduced the problem. You can find it here https://github.com/mniebisch/check_pyfakefs_github_action/runs/7429852799?check_suite_focus=true

Additionally, here's a screenshot showing that everything works just fine locally.
![screenshot](https://user-images.githubusercontent.com/23555906/179996791-1c1ebb9c-3646-4dbd-bc8c-eed601d59314.png)

I hope this isn't a known issue. My Google search didn't turn up any help. If so, I'm sorry :)

**Comment by mrbean-bremen** [comment] 2022-07-20 18:22
Thanks for the report! No, I don't know of this issue, and I have no idea what causes this so far. 
I will have a closer look after I fix a couple of regression bugs that came up recently, so this may take a bit...

**Comment by mrbean-bremen** [comment] 2022-07-23 07:28
@mniebisch - Can you check if it is fixed with master?

**Comment by mniebisch** [comment] 2022-07-25 06:42
@mrbean-bremen - I check with pyfakefs 3.6.3. Unfortunately, it doesn't work.

**Comment by mrbean-bremen** [comment] 2022-07-25 06:45
@mniebisch - it is not integrated into a release yet -can you please check with master?

**Comment by mniebisch** [comment] 2022-07-25 07:01
@mrbean-bremen Ah, my bad :D Seems like I need a coffee. You fixs works like a charm. Thanks a lot for the fast support :) What caused the problem

**Comment by mrbean-bremen** [comment] 2022-07-25 07:11
That's good! I'm not completely sure what caused it as I could not reproduce it locally - I just found the commit and the specific changes that caused this in CI. It seems that accessing `__name__` in non-module objects did not behave as expected (e.g. instead of raising an exception it caused the test to hang). I reintroduced the module check using `inspect`, that I have removed as a performance optimization some time ago. The performance seems not to be affected anyway, at least for newer Python versions.
I will check if I can resolve another open issue and probably make another patch release afterwards.

**Closed** 2022-07-25 09:12 UTC
