### ISSUE TITLE
pyfakefs is incompatible with pytest

### ISSUE THREAD

**Issue by megapctr** [jmcgeheeiv/pyfakefs#43] opened 2015-04-26 16:29 UTC
This is a rather specific issue. To reproduce this, you need to have a failing doctest that uses Patcher.

Example doctest:
```
def foo():
    """
    >>> getfixture('fs')
    >>> foo()
    True
    """
    return False
```

Here's my `fs` fixture:
```
from fake_filesystem_unittest import _Patcher

_Patcher.SKIPNAMES.add('py')  # Ignore pytest components when faking filesystem


@pytest.yield_fixture
def fs():
    """ Fake filesystem. """
    patcher = _Patcher()
    patcher.setUp()
    yield
    patcher.tearDown()
```

Traceback: [pastebin](http://pastebin.com/raw.php?i=WuWj1sck)

Traceback after altering `_Patcher._findModules to skip literally everything: [pastebin](http://pastebin.com/raw.php?i=RaQjLhv2)

I'm not sure whether this error lies within pyfakefs, or can be resolved my adding some pytest submodules to `_Patcher.SKIPNAMES` set.

**Comment by jmcgeheeiv** [comment] 2015-04-26 18:59
Just last night I prepended '_' to _Patcher to signify that it is a private class.  I was not aware that it had an application outside fake_filesystem_unittest.py.  But you did find an application, a pretty cool application, so let's go with that.

It looks to me like _Patcher patched pytest to use the fake filesystem, and in your fake filesystem you have no directory '/home/Filip/renamer'.  You could verify this by creating the fake directory and seeing if it changes the stack trace.

My guess is that _Patcher will need pytest added to SKIPMODULES.  It will also need a name change from _Patcher to Patcher.

**Comment by megapctr** [comment] 2015-04-26 20:51
Adding pytest to SKIPMODULES didn't change a thing. When I create the missing directories in `foo()`, the traceback looks like this:
```
  (...)
  File "/home/Filip/.virtualenvs/renamer/lib/python2.7/site-packages/_pytest/capture.py", line 362, in done
    os.close(targetfd_save)
  File "/home/Filip/pyfakefs/fake_filesystem.py", line 1251, in close
    fh = self.filesystem.GetOpenFile(file_des)
  File "/home/Filip/pyfakefs/fake_filesystem.py", line 416, in GetOpenFile
    raise OSError(errno.EBADF, 'Bad file descriptor', file_des)
OSError: [Errno 9] Bad file descriptor: 5
```

**Comment by jmcgeheeiv** [comment] 2015-04-28 03:50
Can you make me a test?  It very well may have to be a separate file, maybe even run separately by py.test.  However it would be nice to keep all_tests.py execute ALL the tests.

I am thinking that we will have to add pytest to SKIPMODULES, then improve the logic to test for a module and all its descendants, like pytest, pytest.config. pytest.core, pytest.main and so on.  Of course you are welcome to do the fix.

**Comment by megapctr** [comment] 2015-04-28 19:05
I'm not sure if I understand. This test should check if a descendant module is being patched? Should it fail in such case?

**Comment by jmcgeheeiv** [comment] 2015-04-28 20:32
Sorry for the misunderstanding.

Just create a file named something like pytest_test.py.  Without using
pyfakefs, it should:

   - import pytest
   - Execute some simple representative passing pytest test.  This test
   should involve the real file system.

Then, add pyfakefs so that the test is executed on the fake file system.
This should reproduce an error similar to what you reported earlier.

After you make the test, I'll try to make it work with pyfakefs.

**Comment by megapctr** [comment] 2015-04-28 20:55
Okay, I can do that. Just to be clear, a _doctest_ that uses pyfakefs should _fail_ - that's what causes the error.

In the meantime, I've tinkered with the code related to SKIPNAMES. Perhaps these changes could help you with finding the bug: https://github.com/megapctr/pyfakefs/commit/15cc093cf82e13edba9fa281abb81d2929f18281

**Comment by megapctr** [comment] 2015-04-29 19:14
I've pushed the commit with doctest tests: https://github.com/megapctr/pyfakefs/commit/4007591e4d79f92d1e822d05071dd0723dc81e84
Good luck with solving the issue!

**Comment by jmcgeheeiv** [comment] 2015-05-17 17:53
In issue #48 I propose a solution to this issue.

**Comment by jmcgeheeiv** [comment] 2015-09-06 20:22
Per issue #48, I reverted back to using mox3.stubout.  This is valuable for other reasons, but I could not resolve the incompatibility with pytest--I just do not know enough about it.

Still, I think that reverting to mox3 was a necessary first step toward pytest support.  I hope that you or someone else who knows pytest better can drive pytest support to completion.

Note: It appears that adding 'py', 'pytest', '_pytest' to SKIPNAMES is part of the solution.  See fake_filesystem_unittest.py line 115.

**Comment by mrbean-bremen** [comment] 2016-10-08 15:11
I tested this under Windows with the 2 tests that should crash:
```
C:\..\pyfakefs>py.test --doctest-modules pytest_doctest_test.py
============================= test session starts =============================
platform win32 -- Python 2.7.11, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: C:\..\pyfakefs, inifile:
collected 2 items

pytest_doctest_test.py FF

================================== FAILURES ===================================
____________________ [doctest] pytest_doctest_test.crashes ____________________
029         >>> open(name).read() == content
Expected:
    False
Got:
    True

C:\..\pyfakefs\pytest_doctest_test.py:29: DocTestFailure
__________________ [doctest] pytest_doctest_test.crashes_too __________________
028         >>> ) SyntaxError(name, content)
UNEXPECTED EXCEPTION: SyntaxError('invalid syntax', ('<doctest pytest_doctest_test.crashes_too[3]>', 1, 1, ') SyntaxError(name, content)\n'))
Traceback (most recent call last):

  File "c:\python27\Lib\doctest.py", line 1315, in __run

  File "<doctest pytest_doctest_test.crashes_too[3]>", line 1

    ) SyntaxError(name, content)

    ^

SyntaxError: invalid syntax

C:\..\pyfakefs\pytest_doctest_test.py:28: UnexpectedException
========================== 2 failed in 0.11 seconds ===========================
```
and it looks fine to me (tests fail as expected). Did I do something wrong, or is it a Linux-only problem, or maybe it is gone with the current versions of pyfakefs and pytest?
@jmcgeheeiv: Could you please check if the issue persists under Linux in case I did the test right?

**Comment by jmcgeheeiv** [comment] 2016-10-08 16:31
@megapctr, @mrbean-bremen, where is this test?  https://github.com/megapctr/pyfakefs/commit/4007591e4d79f92d1e822d05071dd0723dc81e84 does not exist.

**Comment by megapctr** [comment] 2016-10-08 16:36
Sorry, I must've deleted this repo. And the solution to my problem was just not to use doctests - I realized it's better to keep tests separated from the source code.

**Comment by jmcgeheeiv** [comment] 2016-10-08 16:50
It's nice to hear from you again, @megapctr.  @mrbean-bremen seems to have a copy.  Let's see what he says.

**Comment by mrbean-bremen** [comment] 2016-10-08 16:59
I just used the checked in pytest_doctest_test.py together with conftest.py in pyfakefs root (which I had to adapt slightly as it uses  _Patcher). I understand they are there to reproduce the problem.

**Comment by jmcgeheeiv** [comment] 2016-10-08 18:38
@megapctr, could you comment on what is wrong with our results?

Result on OSX:
```
py.test --doctest-modules pytest_doctest_test.py
================================================== test session starts ==================================================
platform darwin -- Python 3.4.1 -- py-1.4.25 -- pytest-2.6.3
collected 3 items 

pytest_doctest_test.py F..

======================================================= FAILURES ========================================================
__________________________________________ [doctest] pytest_doctest_test.fails __________________________________________
024         """.format(
025         command="getfixture('fs')" if fake else "pass",
026         func_name=func_name,
027         result=result)
028 
029     return make_file
Expected:
    False
Got:
    True

/Users/johnm/git/pyfakefs/pytest_doctest_test.py:29: DocTestFailure
========================================== 1 failed, 2 passed in 0.03 seconds ===========================================
```
Result on Linux:
```
Forthcoming momentarily.
```

**Comment by mrbean-bremen** [comment] 2016-10-08 19:19
@jmcgeheeiv: to test the crashes, you have to comment in the last 2 lines (named 'crashes' and 'crashes_too'). In my test, I commented out the other ones, as these are known to work.

**Comment by jmcgeheeiv** [comment] 2016-10-08 20:36
On OSX and Linux, 'crashes' and 'crashes_too' raise an exception, but nothing more serious.

**Comment by mrbean-bremen** [comment] 2016-10-08 20:52
Can you provide the output for @megapctr? If it really works as expected, we may close the issue.

**Comment by megapctr** [comment] 2016-10-08 22:05
It's really difficult to give an answer since it's been a while since I wrote these tests :) Can you please upload the test file somewhere? I'll check the behavior against master and #129

**Comment by jmcgeheeiv** [comment] 2016-10-08 23:22
Here is the entire output from Linux.  In this output, both `crashes` and `crashes_too` are un-commented.  I discovered that un-commenting just one makes the error message clearer, and of course half as long:
```
py.test --doctest-modules pytest_doctest_test.py
============================= test session starts ==============================
platform linux -- Python 3.4.3 -- py-1.4.26 -- pytest-2.6.4
collected 5 items 

pytest_doctest_test.py Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.4/site-packages/py/_error.py", line 64, in checked_call
    return func(*args, **kwargs)
  File "/home/johnm/git/pyfakefs/pyfakefs/fake_filesystem.py", line 2839, in __call__
    return self.Call(*args, **kwargs)
  File "/home/johnm/git/pyfakefs/pyfakefs/fake_filesystem.py", line 2908, in Call
    raise IOError(errno.ENOENT, 'No such file or directory', file_path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/johnm/git/pyfakefs/pytest_doctest_test.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.4/site-packages/_pytest/main.py", line 84, in wrap_session
    doit(config, session)
  File "/usr/local/anaconda3/lib/python3.4/site-packages/_pytest/main.py", line 122, in _main
    config.hook.pytest_runtestloop(session=session)
  File "/usr/local/anaconda3/lib/python3.4/site-packages/_pytest/core.py", line 413, in __call__
    return self._docall(methods, kwargs)
  File "/usr/local/anaconda3/lib/python3.4/site-packages/_pytest/core.py", line 424, in _docall
    res = mc.execute()
  File "/usr/local/anaconda3/lib/python3.4/site-packages/_pytest/core.py", line 315, in execute
    res = method(**kwargs)
  File "/usr/local/anaconda3/lib/python3.4/site-packages/_pytest/main.py", line 142, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "/usr/local/anaconda3/lib/python3.4/site-packages/_pytest/core.py", line 413, in __call__
    return self._docall(methods, kwargs)
  File "/usr/local/anaconda3/lib/python3.4/site-packages/_pytest/core.py", line 424, in _docall
    res = mc.execute()
  File "/usr/local/anaconda3/lib/python3.4/site-packages/_pytest/core.py", line 315, in execute
    res = method(**kwargs)
  File "/usr/local/anaconda3/lib/python3.4/site-packages/_pytest/runner.py", line 65, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "/usr/local/anaconda3/lib/python3.4/site-packages/_pytest/runner.py", line 75, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "/usr/local/anaconda3/lib/python3.4/site-packages/_pytest/runner.py", line 111, in call_and_report
    report = hook.pytest_runtest_makereport(item=item, call=call)
  File "/usr/local/anaconda3/lib/python3.4/site-packages/_pytest/main.py", line 167, in call_matching_hooks
    return hookmethod.pcall(plugins, **kwargs)
  File "/usr/local/anaconda3/lib/python3.4/site-packages/_pytest/core.py", line 417, in pcall
    return self._docall(methods, kwargs)
  File "/usr/local/anaconda3/lib/python3.4/site-packages/_pytest/core.py", line 424, in _docall
    res = mc.execute()
  File "/usr/local/anaconda3/lib/python3.4/site-packages/_pytest/core.py", line 315, in execute
    res = method(**kwargs)
  File "/usr/local/anaconda3/lib/python3.4/site-packages/_pytest/runner.py", line 214, in pytest_runtest_makereport
    longrepr = item.repr_failure(excinfo)
  File "/usr/local/anaconda3/lib/python3.4/site-packages/_pytest/doctest.py", line 62, in repr_failure
    filelines = py.path.local(filename).readlines(cr=0)
  File "/usr/local/anaconda3/lib/python3.4/site-packages/py/_path/common.py", line 141, in readlines
    content = self.read('rU')
  File "/usr/local/anaconda3/lib/python3.4/site-packages/py/_path/common.py", line 134, in read
    with self.open(mode) as f:
  File "/usr/local/anaconda3/lib/python3.4/site-packages/py/_path/local.py", line 343, in open
    return py.error.checked_call(open, self.strpath, mode)
  File "/usr/local/anaconda3/lib/python3.4/site-packages/py/_error.py", line 84, in checked_call
    raise cls("%s%r" % (func.__name__, args))
py.error.ENOENT: [No such file or directory]: FakeFileOpen('/home/johnm/git/pyfakefs/pytest_doctest_test.py', 'rU')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.4/site-packages/_pytest/main.py", line 96, in wrap_session
    config.notify_exception(excinfo, config.option)
  File "/usr/local/anaconda3/lib/python3.4/site-packages/_pytest/config.py", line 654, in notify_exception
    excinfo=excinfo)
  File "/usr/local/anaconda3/lib/python3.4/site-packages/_pytest/core.py", line 413, in __call__
    return self._docall(methods, kwargs)
  File "/usr/local/anaconda3/lib/python3.4/site-packages/_pytest/core.py", line 424, in _docall
    res = mc.execute()
  File "/usr/local/anaconda3/lib/python3.4/site-packages/_pytest/core.py", line 315, in execute
    res = method(**kwargs)
  File "/usr/local/anaconda3/lib/python3.4/site-packages/_pytest/capture.py", line 149, in pytest_internalerror
    self.reset_capturings()
  File "/usr/local/anaconda3/lib/python3.4/site-packages/_pytest/capture.py", line 84, in reset_capturings
    cap.stop_capturing()
  File "/usr/local/anaconda3/lib/python3.4/site-packages/_pytest/capture.py", line 296, in stop_capturing
    self.out.done()
  File "/usr/local/anaconda3/lib/python3.4/site-packages/_pytest/capture.py", line 367, in done
    os.close(targetfd_save)
  File "/home/johnm/git/pyfakefs/pyfakefs/fake_filesystem.py", line 1825, in close
    fh = self.filesystem.GetOpenFile(file_des)
  File "/home/johnm/git/pyfakefs/pyfakefs/fake_filesystem.py", line 680, in GetOpenFile
    raise OSError(errno.EBADF, 'Bad file descriptor', file_des)
OSError: [Errno 9] Bad file descriptor: 6

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/johnm/git/pyfakefs/pyfakefs/fake_filesystem.py", line 1157, in GetObjectFromNormalizedPath
    target_object = target_object.GetEntry(component)
  File "/home/johnm/git/pyfakefs/pyfakefs/fake_filesystem.py", line 420, in GetEntry
    return self.contents[pathname_name]
KeyError: 'home'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/johnm/git/pyfakefs/pyfakefs/fake_filesystem.py", line 1913, in _ConfirmDir
    directory = self.filesystem.GetObject(target_directory)
  File "/home/johnm/git/pyfakefs/pyfakefs/fake_filesystem.py", line 1177, in GetObject
    return self.GetObjectFromNormalizedPath(file_path)
  File "/home/johnm/git/pyfakefs/pyfakefs/fake_filesystem.py", line 1161, in GetObjectFromNormalizedPath
    file_path)
FileNotFoundError: [Errno 2] No such file or directory in fake filesystem: '/home/johnm/git/pyfakefs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.4/site-packages/py/_error.py", line 64, in checked_call
    return func(*args, **kwargs)
  File "/home/johnm/git/pyfakefs/pyfakefs/fake_filesystem.py", line 1951, in chdir
    self._ConfirmDir(target_directory)
  File "/home/johnm/git/pyfakefs/pyfakefs/fake_filesystem.py", line 1915, in _ConfirmDir
    raise OSError(e.errno, e.strerror, target_directory)
FileNotFoundError: [Errno 2] No such file or directory in fake filesystem: '/home/johnm/git/pyfakefs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/anaconda3/bin/py.test", line 6, in <module>
    sys.exit(main())
  File "/usr/local/anaconda3/lib/python3.4/site-packages/_pytest/config.py", line 41, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/usr/local/anaconda3/lib/python3.4/site-packages/_pytest/core.py", line 413, in __call__
    return self._docall(methods, kwargs)
  File "/usr/local/anaconda3/lib/python3.4/site-packages/_pytest/core.py", line 424, in _docall
    res = mc.execute()
  File "/usr/local/anaconda3/lib/python3.4/site-packages/_pytest/core.py", line 315, in execute
    res = method(**kwargs)
  File "/usr/local/anaconda3/lib/python3.4/site-packages/_pytest/main.py", line 116, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/usr/local/anaconda3/lib/python3.4/site-packages/_pytest/main.py", line 105, in wrap_session
    session.startdir.chdir()
  File "/usr/local/anaconda3/lib/python3.4/site-packages/py/_path/local.py", line 543, in chdir
    py.error.checked_call(os.chdir, self.strpath)
  File "/usr/local/anaconda3/lib/python3.4/site-packages/py/_error.py", line 84, in checked_call
    raise cls("%s%r" % (func.__name__, args))
py.error.ENOENT: [No such file or directory]: chdir('/home/johnm/git/pyfakefs',)
```

**Comment by mrbean-bremen** [comment] 2016-10-09 07:16
Ok, I noticed the discrepancy between pytest versions in our tests (2.6.4 vs 2.9.2).
I now tested with older pytest versions under Windoiws and got the same exceptions. They are gone if using a pytest version >= 2.8.6, though I couldn't find anything that looks related in the pytest release notes.
@jmcgeheeiv: please make one final test with a newer pytest version under Linux or MacOS X. If this works as expected (see the output under Windows above) I propose to close this issue if thats ok with @megapctr. Maybe we should mention something in the documentation about the pytest version needed for doc tests.
Note that the __name__ attribute is also not needed in this case.

**Comment by megapctr** [comment] 2016-10-09 15:20
I just checked the `pytest-support` branch, it seems to work as expected, including syntax error in doctests :tada:

**Comment by mrbean-bremen** [comment] 2016-10-09 15:35
As the problem seems to have been fixed in pytest 2.8.6, and it should usually not be a problem to upgrade to this or a newer version, I would say it's OK. Thanks for the tests!

**Comment by jmcgeheeiv** [comment] 2016-10-09 16:59
Indeed I have PyTest 2.6.3 installed.  I will document this PyTest version dependency relying on your analyses.

Since the real `open()` has `__name__`, let's leave it in,
```
>>> open.__name__
'open'
```
but leave it set to "FakeOpenFile".  As we saw in this issue, knowing the difference can provide diagnostic clues.

**Comment by mrbean-bremen** [comment] 2016-10-09 17:11
That sounds good. May be it makes sense to leave the example code for pytest there (without mentioning the crash and with a mention of the needed pytest version instead).

**Closed** 2016-10-09 17:25 UTC
Labels: help wanted
