### ISSUE TITLE
AttributeError: 'FakePipeWrapper' object has no attribute 'readable'

### ISSUE THREAD

**Issue by MasterSergius** [jmcgeheeiv/pyfakefs#650] opened 2021-12-03 14:29 UTC
**Describe the bug**
I have a set of tests using fake fs and vcr cassetess. When I try to run it, I have the following error:
```py
            if c2pread != -1:
                self.stdout = io.open(c2pread, 'rb', bufsize)
                if self.text_mode:
>                   self.stdout = io.TextIOWrapper(self.stdout,
                            encoding=encoding, errors=errors)
E                           AttributeError: 'FakePipeWrapper' object has no attribute 'readable'
subprocess.py:850: AttributeError
```
This error appeared when I tried to run tests in a bit newer environment:
```sh
Python              3.8.12
-----------------------
pyfakefs           4.5.3
pytest              6.2.5
pytest-asyncio     0.16.0
pytest-mock        3.6.1
pytest-recording   0.12.0
```
It works within the following (older) environment:
```sh
Python              3.8.2
-----------------------
pyfakefs                          4.3.0
pytest                            6.1.2
pytest-asyncio                    0.14.0
pytest-mock                       3.3.1
pytest-recording                  0.10.0
```

**How To Reproduce**
pytest --record-mode=once tests

**Comment by mrbean-bremen** [comment] 2021-12-03 15:00
Hm, can you show your actual test, or a minimal reproducible example? Are you using `subprocess` or `multiprocessing` in your tested code? Both are known to [have problems with pyfakefs](http://jmcgeheeiv.github.io/pyfakefs/master/usage.html#modules-not-working-with-pyfakefs).

**Comment by MasterSergius** [comment] 2021-12-03 15:05
Ok, I wanted to contribute to this library https://github.com/okta/okta-sdk-python, so I tried to run tests if everything is fine, you can check tests/integration folder

**Comment by mrbean-bremen** [comment] 2021-12-03 15:09
Ok, I will check if I can reproduce it, thanks.

**Comment by mrbean-bremen** [comment] 2021-12-03 15:32
What OS you are using? I'm currently under Windows, and here this is not reproducible with the same environment.

**Comment by MasterSergius** [comment] 2021-12-03 15:33
MacOS 10.15.17

**Comment by mrbean-bremen** [comment] 2021-12-03 15:44
Ok, I just checked their own [CI tests](https://github.com/okta/okta-sdk-python/runs/4385651307) which use the same versions under Ubuntu and also work, so I guess this is a MacOS-specific problem. Unfortunately, I don't have a Mac, so I'm not sure how to reproduce this, but I'm afraid it has to with `subprocess` using some OS-specific functions. As mentioned, `subprocess` does not always work with pyfakefs due to that (pyfakefs cannot only patch Python functions, not C functions), and I just noticed that the callstack is indeed in `subprocess.py`. I will have a look at that code, but I'm afraid that you are out of luck here. 
If you want to contribute to that repo, you probably have to rely on their CI for the time being.

**Comment by mrbean-bremen** [comment] 2021-12-03 16:08
I checked the code, and I may actually be able to fix this - maybe all it takes is to patch a couple of functions for the fake pipe.  I cannot guarantee that it will work after the fix, but we can try it.

**Comment by MasterSergius** [comment] 2021-12-03 16:15
@mrbean-bremen ok, anyway, thank you for the fast response

**Comment by mrbean-bremen** [comment] 2021-12-03 17:40
@MasterSergius - can you please check how it behaves with pyfakefs master?

**Comment by MasterSergius** [comment] 2021-12-06 09:20
@mrbean-bremen Looks fine

**Comment by mrbean-bremen** [comment] 2021-12-06 10:21
Ok, thanks - do you need a patch release?

**Comment by MasterSergius** [comment] 2021-12-06 13:50
No, I can use it now, so you can release when u're ready to.

**Comment by mrbean-bremen** [comment] 2021-12-06 14:55
Ok, thanks - closing this then.

**Closed by mrbean-bremen** 2021-12-06 14:55 UTC

**Comment by julienschuermans** [comment] 2022-01-12 10:41
Hi @mrbean-bremen, thanks for your amazing work!
I've got the same issue. When are you planning to release the fix?

**Comment by mrbean-bremen** [comment] 2022-01-12 10:44
I can make a patch release tonight, if you need it.

**Comment by julienschuermans** [comment] 2022-01-12 11:01
That would be great, thanks a lot!

**Comment by mrbean-bremen** [comment] 2022-01-12 16:34
Ok, [done](https://pypi.org/project/pyfakefs/4.5.4/).
