### ISSUE TITLE
open difference in exceptions raised (another trailing separator problem)

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#369] opened 2018-04-09 15:44 UTC
```
import shutil
import pyfakefs.fake_filesystem
import os

ROOT_PATH = "/Volumes/ramdisk/newtest"

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/newtest')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)
opener0 = pyfakefs.fake_filesystem.FakeFileOpen(fs)

if False:
    os0 = os
    opener0 = open
    shutil.rmtree(ROOT_PATH)
    os.mkdir(ROOT_PATH)

component0 = "alpha" 
component1 = "" 
path0 = ROOT_PATH 
path0 += os.path.sep + component0 
path0 += os.path.sep + component1 
file0 = opener0(path0,'w') 
```

OSError for pyfakefs, IOError for Python

**Comment by mrbean-bremen** [comment] 2018-04-09 17:53
This is an exact duplicate of #362. As we have regression tests for this one, I guess it is a mistake - closing.

**Closed by mrbean-bremen** 2018-04-09 17:53 UTC
Labels: TSTL
