### ISSUE TITLE
TypeError: an integer is requires

### ISSUE THREAD

**Issue by ut-adamc** [jmcgeheeiv/pyfakefs#305] opened 2017-10-09 15:02 UTC
Example code:
```
import os

from pyfakefs.fake_filesystem_unittest import Patcher


contents = {0: "abc", 1: "def", 2: "xyz"}

def main():
    mockdir = '/mockdir'
    paths = []
    patcher = Patcher()
    patcher.setUp()
    fs = patcher.fs
    fs.MakeDirectory(mockdir)

    for key, val in contents.items():
        path = os.path.join(mockdir, 'file_{0}'.format(key))
        paths.append(path)
        fs.CreateFile(path, val)

    for path in paths:
        os.path.exists(path) # will raise TypeError: an integer is required

if __name__ == '__main__':
    main()
```

**Comment by mrbean-bremen** [comment] 2017-10-09 16:43
`CreateFile()` uses `st_mode` as second parameter, thus leading to the error. You want
``` python
    fs.CreateFile(path, contents=val)
```

instead.

**Comment by mrbean-bremen** [comment] 2017-10-09 17:44
You are welcome! Can we close this issue?

**Comment by mrbean-bremen** [comment] 2017-10-11 22:00
Closing as not a bug.

**Closed by mrbean-bremen** 2017-10-11 22:00 UTC
