### ISSUE TITLE
Try and fake pathlib2 before pathlib

### ISSUE THREAD

**Issue by peteboothroyd** [jmcgeheeiv/pyfakefs#462] opened 2018-12-21 15:36 UTC
**Is your feature request related to a problem? Please describe.**
pathlib2 is only used if pathlib is not found. As pathlib is now included for python>=3.4 pathlib2 will not be faked for these newer versions of python even if it is present in a project. As I understand it the 'correct' usage of pathlib2 is not to use conditional imports such as in the `extra_packages.py` as highlighted in this [issue](https://github.com/mcmtroffaes/pathlib2/issues/8) on the pathlib2 repo, but rather to use pathlib2 directly in place of pathlib where compatibility between different python versions is required.

This means (AFAIK) that if I want to use pathlib2 in my project and have it faked I have to use the Patcher and modules_to_patch option - and then have to reload certain modules as a result.

**Describe the solution you'd like**
I think it would be better to flip the logic in `extra_packages.py` to first try and load pathlib2 and then only if this is not present to load pathlib. pathlib2 has to be explicitly downloaded whereas pathlib is included in the standard library so there should be fewer instances where the wrong module is patched. Alternatively I don't know if it would be possible/advisable to patch both modules with the faked module?

**Comment by mrbean-bremen** [comment] 2018-12-21 15:57
> I think it would be better to flip the logic in extra_packages.py to first try and load pathlib2 and then only if this is not present to load pathlib. 

This sounds reasonable, I have to think a bit about this.

> Alternatively I don't know if it would be possible/advisable to patch both modules with the faked module?

I don't think this would be good idea - you don't want to mix both libraries in the same project, so that should not be needed.

I will look at this some time later...

**Comment by mrbean-bremen** [comment] 2018-12-23 19:43
Ok, I just checked the pathlib2 issue you mentioned, and agree that the change certainly would make sense.
I may have a look somewhere in the next week (or in the next year...)

**Comment by mrbean-bremen** [comment] 2018-12-26 18:41
@peteboothroyd - I changed the order of import as proposed - please check if this is what you need.

**Comment by peteboothroyd** [comment] 2019-01-02 14:33
I think there are some errors in fake_pathlib.py as some of the classes inherit from pathlib.Path, however if pathlib2 is imported successfully then pathlib is set to None.

**Comment by mrbean-bremen** [comment] 2019-01-02 15:13
Ah, ok - I don't understand why this did not come up in the tests. Hm, maybe it will happen only for Python>3.4, where `pathlib2` is not tested - I will check this.

**Comment by mrbean-bremen** [comment] 2019-01-02 20:09
Ok, I changed the code accordingly - hopefully correctly this time. Please check again.

**Comment by peteboothroyd** [comment] 2019-01-03 09:13
Yes that seems to be working perfectly for me! Appreciate the help :)

**Comment by peteboothroyd** [comment] 2019-01-03 09:17
Would it be possible to get a new PyPi release?

**Comment by mrbean-bremen** [comment] 2019-01-03 09:31
Hm, maybe I will a bit to check if anything else comes up...

**Comment by mrbean-bremen** [comment] 2019-01-13 13:32
Ok, nothing came up, so I made a new PyPi release (something will come up tomorrow for sure...)
Closing.

**Closed by mrbean-bremen** 2019-01-13 13:32 UTC
Labels: enhancement

**Comment by mrbean-bremen** [comment] 2019-02-05 21:40
@peteboothroyd - I made some changes to the `pathlib` handling in master due to a regression I introduced with the changes for this issue. It would be nice if you could check if the current master still works for you (regarding pathlib/pathlib3), before I make another release with the change.
