### ISSUE TITLE
read after os.open with O_TRUNC (MacOS/Python 2 only)

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#277] opened 2017-07-16 21:43 UTC
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')	
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)
opener0 = pyfakefs.fake_filesystem.FakeFileOpen(fs)

component0 = "alpha" 
path0 = "/Volumes/ramdisk/test" 
path0 += "/" + component0 
str0 = "" 
str0 += 'l' 
fd0 = os0.open(path0, os.O_CREAT | os.O_WRONLY | os.O_TRUNC | os.O_EXCL) 
file0 = opener0(path0) 
result = file0.read() 
os0.write(fd0,str0) 
result = file0.read() 
print result

This seems tricky; that the file is opened O_EXCL in the operating system, but then is opened with open... it's not clear what the right semantics really is, but you don't match Python

**Comment by mrbean-bremen** [comment] 2017-07-29 17:43
Can't reproduce this one - I get an empty string for the first read, and 'l' for the second in pyfakefs and python, both in Windows in Linux.

**Comment by mrbean-bremen** [comment] 2017-07-31 07:35
@agroce - please check if you get the time, not sure if this an MacOS issue, or I did something wrong in the test. 
I'm currently mostly working on another project, and ignoring the multiple FD issues in pyfakefs for the time being. I will check any other issues, however, if something pops up.

**Comment by agroce** [comment] 2017-07-31 21:05
I definitely get 'l' (pyfakefs) vs '' (os) on MacOS.  But on linux, I get 'l' from the os.

I'm mostly not working on this, due to some other deadlines, but will get back to some issues with normal python IO before too long (I've seen them in some experiments, but actually need them in place for the experiments!)

**Comment by agroce** [comment] 2017-07-31 21:10
If you wanted those slides from ISSTA, email me (agroce@gmail.com) an email I can send a zip too -- I'll throw in the paper draft that's using these experiments, which might interest you also.

**Comment by mrbean-bremen** [comment] 2017-07-31 21:21
Ok, thank you! I will ignore these issues, as I said - I think these are quite unlikely use cases, and I have no idea how to handle them (as I don't understand the behavior).

**Comment by mrbean-bremen** [comment] 2018-02-11 12:07
I did some re-evaluation of this issue, and decided that it is not worth fixing it - I consider it more of a bug in the implementation  under MacOS and Python 2. 
It happens, if creating a file for writing using `os.open()` (the exclusive flag is irrelevant to this), then opening it using `open()`, reading from the file, then writing using `os.write` and reading again. It does not happen, if skipping the first `read()`, so it seems to be some issue with internal buffering after the first `read()`.
Setting "wontfix" label.

**Comment by mrbean-bremen** [comment] 2019-11-24 18:47
Closing as obsolete - no more Python 2 support.

**Closed by mrbean-bremen** 2019-11-24 18:47 UTC
Labels: TSTL, wontfix
